image: kroniak/ssh-client
variables:
  GIT_STRATEGY: none

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan tyers.io >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - Deploy

docker build:
  stage: Deploy
  script:
    - |
      ssh server@tyers.io <<'ENDSSH'
      cd /var/www/apps/rain
      npm i
      npm run build
      ENDSSH
  only:
    refs:
      - master
